### ISSUE TITLE
Suddenly my page not getting rendered, I am using PyScript link.

### ISSUE THREAD

**Issue by Siddharth1India** [pyscript/pyscript#427]
I am working on this project since yesterday and everything was fine until now. Now I am getting text inside PyScript tag as output.

Before:
![image](https://user-images.githubusercontent.com/46651743/169333163-58e87969-35ae-4829-ad83-840c76ae1534.png)

Now:
![image](https://user-images.githubusercontent.com/46651743/169333317-9279cdb4-7609-4f10-b3e5-f06c87ebfe44.png)

Console now:
![image](https://user-images.githubusercontent.com/46651743/169333570-406c4184-2e71-45bc-af6c-933b31c18ba2.png)

Am I making any mistake?

**Comment by marimeireles** [comment]
You didn't change your code at all?
Just downloaded a new version of PyScript?

**Comment by Siddharth1India** [comment]
> You didn't change your code at all? Just downloaded a new version of PyScript?

I don't think I made any change. Just to be sure, I tried running my old pyscript project. That too showing same issue.
Also, I am using links to get PyScript so no issue of version.
![image](https://user-images.githubusercontent.com/46651743/169337224-2417d529-0802-45be-97df-6adfd1eb0e25.png)

Also, getting started example on official repo (Pi value) is not loading correctly.
![image](https://user-images.githubusercontent.com/46651743/169337400-ba9d0a21-4f97-4405-b5d6-d156f7640f64.png)

**Comment by siddhi** [comment]
I have the same problem. Everything was working until an hour ago.

**Comment by diamondzxd** [comment]
I was trying PyScript today for the first time, and code is getting rendered as it is, I was banging my head since past 30 minutes till I saw this thread now.

I'm not the only one (:

**Comment by siddhi** [comment]
Try this - https://siddhi.github.io/pyscript/tictactoe.html

It was working yesterday and I haven't touched it since

**Comment by Siddharth1India** [comment]
Thanks @marimeireles @siddhi @diamondzxd 
As issue is found, closing this issue.

**Comment by marimeireles** [comment]
Should be fixed soon! Kudos to @pww217 🎉

**Comment by marimeireles** [comment]
Something is still not right.
Are you able to run your examples? @Siddharth1India or @diamondzxd?
Weirdly enough running @siddhi's example works for me, but not our own examples.

**Comment by nico-bohlinger** [comment]
The simple example from https://github.com/pyscript/pyscript/blob/main/docs/tutorials/getting-started.md is still not working for me:
```html
<html>
  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
  </head>
  <body> <py-script> print('Hello, World!') </py-script> </body>
</html>
```

**Comment by marimeireles** [comment]
Alright, so my browsers must be caching stuff somehow.
Thanks for the input. =)

**Comment by pww217** [comment]
I think it's a problem with the CDN still caching the old build - troubleshooting now.

**Comment by diamondzxd** [comment]
Nope, still no luck. Even running a print('Hello World') renders as it is.

**Comment by marianoweber** [comment]
I don't see #322 being the problem in this case. 
Can anyone explain why it should be the problem except for being the most recent merge?

**Comment by donnynja** [comment]
my code is this:
`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>replit</title>
  <link href="style.css" rel="stylesheet" type="text/css" />
  <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
</head>
update this page
<body>
  <py-env>
    - os
  </py-env>
  <py-script src= "./python scripts/test_file.py"></py-script>
  <br>
  <py-script>
print("pyscript works")
  </py-script>
  <a href="pages/page1.html">test page</a>
  <script src="script.js"></script>
</body>
</html>
`
and the output is this:
![da cancellare](https://user-images.githubusercontent.com/96085270/169356329-fcbe48ba-0dea-4660-b363-3f07b65b7364.PNG)

I'm pretty sure that i shouldn't show on the console the print command and should write the stuff that is coming from the linked file, however, i aknoledge the fact that you are working hard for fixing this issue and don't want to put you in a rush

**Comment by donnynja** [comment]
> Nope, still no luck. Even running a print('Hello World') renders as it is.

same

**Comment by pww217** [comment]
At this point pyscript.js and pyscript.css should be served from the origin which has been reverted to https://github.com/pyscript/pyscript/commit/59fc66765195d95db17224e70113c17747f88fbb

**Comment by donnynja** [comment]
if you want I'll try to run my code again and see if it works

**Comment by diamondzxd** [comment]
> At this point pyscript.js and pyscript.css should be served from the origin which has been reverted to [59fc667](https://github.com/pyscript/pyscript/commit/59fc66765195d95db17224e70113c17747f88fbb)

Don't see any improvements right now, I guess will wait for the CDN cache to purge as well..

**Comment by afriza1** [comment]
I tried some examples and it didn't work. So i saw this problem in my chrome

![Screenshot_20220520_002207](https://user-images.githubusercontent.com/41586762/169360337-3bed3b45-ede3-4df6-8712-70e7a798378a.png)

[Samesite cookie explained](https://web.dev/samesite-cookies-explained/?utm_source=devtools)

**Comment by xX7912Xx** [comment]
Same problem.
It was working yesterday.
link: http://www.dotcs.community/PyScript/DCSSDP.html
I didn't change my .html file.

Here are some screenshots:
2022.05.15:
![0CG7`J9%LG11E1K81@HH_@1](https://user-images.githubusercontent.com/60053890/169353531-009b4c3a-7e3e-4dc2-bf9c-1f0e664490e9.jpg)
![26UQK3TS2%~Z~CSN$9UM6@R](https://user-images.githubusercontent.com/60053890/169353439-162a1faa-026c-46d9-ae0a-e5c99968193e.jpg)

Now:
![image](https://user-images.githubusercontent.com/60053890/169351785-588695d0-3cd7-4f63-b815-3f0c4f0b2fb0.png)![image](https://user-images.githubusercontent.com/60053890/169351656-d9e53262-f13f-44a5-8904-54a10fde60f4.png)
![image](https://user-images.githubusercontent.com/60053890/169351837-15fbe876-875c-4f1a-b8e4-2b50dfcb25f3.png)

**Comment by manatlan** [comment]
it could be cool if urls were versionned (ex: "https://pyscript.net/v0/pyscript.js")

**Comment by afriza1** [comment]
I think it must be like bootstrap does, has some property named integrity and crossorigin in their cdn ?

`<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">`

`<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>`

**Comment by afriza1** [comment]
Mine hasn't :(
![Screenshot_20220520_010916](https://user-images.githubusercontent.com/41586762/169370696-7af2b74a-7862-4661-b620-a8af64c15121.png)

**Comment by pk1on** [comment]
Same
![Screenshot (85)](https://user-images.githubusercontent.com/92085410/169371395-6616da41-e020-4f5d-a77f-d79286f57cc2.png)

**Comment by pww217** [comment]
So we fixed this by uploading a local build to /alpha. If it's not working for you, please use incognito and/or clear your browser and cookie cache!

If you still have this issue please reply here. If it's another issue, please open a new one.

**Comment by diamondzxd** [comment]
Works now..

Thanks!

**Comment by pww217** [comment]
What happened:

This was a combination of a couple mistakes and some bad luck.

pyscript.net/alpha/ is only meant to update on tags, not on every merge into main. Unfortunately it was doing it on every merge due to a CI misconfiguration. This has been fixed already.

Something in the CI environment changed so while I reverted the git ref to a previous commit as mentioned above, it was still having the same issue once built. This is apparently because of a change in the CI - a dependency, environment, or otherwise. This is what we will need to investigate in the UNSTABLE branch where such breaks belong. This also is a good example of why it's important to pin dependencies and other versions, which we will open a new issue to work on too!

Fun note: I was working on testing in the CI and the PR for that [actually caught this](https://github.com/pyscript/pyscript/runs/6509767106?check_suite_focus=true)! Unfortunately, having not yet been merged it did not catch it in time. It will however merged soon and everyone who worked on the testing gets big kudos in advance because:

The testing works! So no pushes that break alpha should go out again (famous last words). 🤞🏼 

I want to thank you all for the reports, input, and help troubleshooting as well as your patience. This was a good chance to learn some of our pain points and address them as this project moves forwards at a very quick pace.

Will leave issue open for a short time in case anyone is still affected (remember to clear those caches!).

**Comment by donnynja** [comment]
hurray! now it gives me another error!
(don't worry, it's a problem in my code, not yours, i'm just happy to see some changes, it means i am going forward)
btw thank you for the  quick responses, you guys are really quick

**Comment by Siddharth1India** [comment]
[SOLVED] Confirming issue solved.
Checked on multiple projects. Everything is fine.

Note: If not working for someone, please clear browser cache and try again.

Keeping issue open for few more hours incase anyone face issue. Will close soon...

**Comment by Hong2024win** [comment]
It doesn't work.
