### ISSUE TITLE
Prepopulating a script or repl wit less or greater than is not correctly parsed:  `12 < 13` -- `12 &lt; 13`

### ISSUE THREAD

**Issue by andre-dietrich** [pyscript/pyscript#480]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help

### What happened?

When adding less than or greater than chars into a `<py-repl>` or a `<py-script>`, it get's escaped with HTML syntax, which causes the code not to run:

``` html
<py-repl> 12 < 13 </py-repl>
```
is printed as:
![image](https://user-images.githubusercontent.com/3089101/171141580-f2f556c5-6572-4f3f-967e-be690927adc9.png)

This can be easily solved by reading the code not via `innerHTML` but `innerText` instead

**Comment by RSMuthu** [comment]
issue is not just for `<` or `>`, it is in generic for all HTML symbols.

When i used `<py-repl>13 & 5</py-rel>` it would return a `&amp;`

<img width="621" alt="image" src="https://user-images.githubusercontent.com/5181808/171256423-7e9e7840-b8a0-495c-b6db-683c35e93a2d.png">

So we need to make the code changes more generic to handle all such scenarios

**Comment by marimeireles** [comment]
Thanks for the input @RSMuthu! If you want to chime in in the PR, please feel welcomed to =)

**Comment by RSMuthu** [comment]
@marimeireles  sure thanks. I would love to contribute. I will update on the pull request of @andre-dietrich

**Comment by andre-dietrich** [comment]
@marimeireles @marimeireles  ... Just updated the PR... I think now, instead of reading the content with `innerHTML`, the `textContent` method does the job in all cases ...

**Comment by RSMuthu** [comment]
Yea sure @andre-dietrich , `dom.textContent` should cover that part.

**Comment by rayjolt** [comment]
Note: this is related to #373.

**Comment by andre-dietrich** [comment]
It seems that there is another problem with backslash escape for " and ' as mentioned here:

https://github.com/LiaBooks/How-To-Code-in-Python-3/issues/1

locally I have fixed this, if it is required, I could update my PR?

**Comment by rod2ik** [comment]
We are still having this problem. Is this normal (a couple of days after fix) ? cdn?

**Comment by marimeireles** [comment]
Oh, thanks for that @rod2ik, will check it again. Sorry your issue was closed without a fix.
